config:
  varzeapro-infra:domain: varzeapro.online
  varzeapro-infra:githubRepo: https://github.com/TCC-CAS/tcc-2025-1-e-2-novus-gateway.git
  varzeapro-infra:githubBranch: main
  varzeapro-infra:sshPublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID6KZXgbm6OKhzzTOXchqa8qb13ZjAxEKOTWQiz+34cE diogo@diogo-pc
  varzeapro-infra:postgresPassword:
    secure: AAABAGMWUl2mfNIqerGHzlty08I5pxxFWiSlFJx569QMVdwSEMb2VQIjUKjN02P2mjBaneJ3AThShiHIDNqhUA==
  varzeapro-infra:jwtSecret:
    secure: AAABAJZSB6lNAUQnRAHO7XLDRdq8eW59VvQBgePBiO2fn+X7DSl08JqWoEHpEk25PzhAkMxgJTgK4FDPyrFGoojl5kiTnGcZqmF9/xfCtBs0Pori2sqlql7SF6jNW+VE
  varzeapro-infra:betterAuthSecret:
    secure: AAABAJZSB6lNAUQnRAHO7XLDRdq8eW59VvQBgePBiO2fn+X7DSl08JqWoEHpEk25PzhAkMxgJTgK4FDPyrFGoojl5kiTnGcZqmF9/xfCtBs0Pori2sqlql7SF6jNW+VE

# Secrets — NÃO coloque aqui, use o CLI:
# pulumi config set --secret postgresPassword "$(openssl rand -hex 16)"
# pulumi config set --secret jwtSecret "$(openssl rand -hex 32)"
# pulumi config set --secret betterAuthSecret "$(openssl rand -hex 32)"
# pulumi config set --secret s3SecretAccessKey "xxx"
# pulumi config set --secret resendApiKey "re_xxx"
# pulumi config set --secret mercadopagoAccessToken "xxx"